// Generated by gencpp from file custom_pkg/custom_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_PKG_MESSAGE_CUSTOM_MSG_H
#define CUSTOM_PKG_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <geometry_msgs/Pose2D.h>

namespace custom_pkg
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : header()
    , name()
    , num(0)
    , loc()  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , num(0)
    , loc(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::String_<ContainerAllocator>  _name_type;
  _name_type name;

   typedef uint32_t _num_type;
  _num_type num;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _loc_type;
  _loc_type loc;





  typedef boost::shared_ptr< ::custom_pkg::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_pkg::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::custom_pkg::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::custom_pkg::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::custom_pkg::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_pkg::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_pkg::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_pkg::custom_msg_<ContainerAllocator1> & lhs, const ::custom_pkg::custom_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.num == rhs.num &&
    lhs.loc == rhs.loc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_pkg::custom_msg_<ContainerAllocator1> & lhs, const ::custom_pkg::custom_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_pkg::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_pkg::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_pkg::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_pkg::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_pkg::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_pkg::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_pkg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b289744901eeb6b737f55c78399b4ed";
  }

  static const char* value(const ::custom_pkg::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b289744901eeb6bULL;
  static const uint64_t static_value2 = 0x737f55c78399b4edULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_pkg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_pkg/custom_msg";
  }

  static const char* value(const ::custom_pkg::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_pkg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/String name\n"
"uint32 num\n"
"geometry_msgs/Pose2D loc\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::custom_pkg::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_pkg::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.num);
      stream.next(m.loc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_pkg::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_pkg::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.name);
    s << indent << "num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num);
    s << indent << "loc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.loc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_PKG_MESSAGE_CUSTOM_MSG_H
